version: '2'

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:latest
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./logs/myapp:/var/log/myapp
      - ./log/myapp/myapp.log:/var/log/myapp/myapp.log
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: influxdb:latest
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./etc/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
  # Define a Chronograf service
  chronograf:
    image: chronograf:latest
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "10000:10000"
      - "8888:8888"
    links:
      - influxdb
